# list of data events lacework does not store
# from https://github.com/lacework-dev/sgm/blob/33951f35d7a8bd3ee0dd31c92f83cc77dfb80ad2/sgm/ciem/awsactions/cloudtraildataevents.go#L11

data_events = [
	# Amazon DynamoDB: AWS::DynamoDB::Table
	"dynamodb:BatchGetItem",
	"dynamodb:BatchWriteItem",
	"dynamodb:DeleteItem",
	"dynamodb:GetItem",
	"dynamodb:PutItem",
	"dynamodb:Query",
	"dynamodb:Scan",
	"dynamodb:UpdateItem",

	# Amazon DynamoDB: API actions (not IAM actions)
	# "dynamodb:BatchExecuteStatement"
	# "dynamodb:ExecuteStatement",
	# "dynamodb:ExecuteTransaction",
	# "dynamodb:TransactGetItems",
	# "dynamodb:TransactWriteItems",

	# Amazon DynamoDB: AWS::DynamoDB::Stream
	"dynamodb:GetRecords",
	"dynamodb:GetShardIterator",

	# AWS Lambda: AWS::Lambda::Function
	"lambda:InvokeAsync",
	"lambda:InvokeFunction",
	"lambda:InvokeFunctionUrl",

	# Amazon S3: AWS::S3::Object
	# Amazon S3: AWS::S3::AccessPoint
	"s3:DeleteObject",
	"s3:DeleteObjectTagging",
	"s3:DeleteObjectVersion",
	"s3:DeleteObjectVersionTagging",
	"s3:GetObject",
	"s3:GetObjectAcl",
	"s3:GetObjectAttributes",
	"s3:GetObjectLegalHold",
	"s3:GetObjectRetention",
	"s3:GetObjectTagging",
	"s3:GetObjectTorrent",
	"s3:GetObjectVersion",
	"s3:GetObjectVersionAcl",
	"s3:GetObjectVersionAttributes",
	"s3:GetObjectVersionForReplication",
	"s3:GetObjectVersionTagging",
	"s3:GetObjectVersionTorrent",
	"s3:PutObject",
	"s3:PutObjectAcl",
	"s3:PutObjectLegalHold",
	"s3:PutObjectRetention",
	"s3:PutObjectTagging",
	"s3:PutObjectVersionAcl",
	"s3:PutObjectVersionTagging",
	"s3:ReplicateObject",
	"s3:RestoreObject",

	# Amazon S3: AWS::S3ObjectLambda::AccessPoint
	"s3-object-lambda:DeleteObject",
	"s3-object-lambda:DeleteObjectTagging",
	"s3-object-lambda:DeleteObjectVersion",
	"s3-object-lambda:DeleteObjectVersionTagging",
	"s3-object-lambda:GetObject",
	"s3-object-lambda:GetObjectAcl",
	"s3-object-lambda:GetObjectAttributes",
	"s3-object-lambda:GetObjectLegalHold",
	"s3-object-lambda:GetObjectRetention",
	"s3-object-lambda:GetObjectTagging",
	"s3-object-lambda:GetObjectTorrent",
	"s3-object-lambda:GetObjectVersion",
	"s3-object-lambda:GetObjectVersionAcl",
	"s3-object-lambda:GetObjectVersionAttributes",
	"s3-object-lambda:GetObjectVersionForReplication",
	"s3-object-lambda:GetObjectVersionTagging",
	"s3-object-lambda:GetObjectVersionTorrent",
	"s3-object-lambda:PutObject",
	"s3-object-lambda:PutObjectAcl",
	"s3-object-lambda:PutObjectLegalHold",
	"s3-object-lambda:PutObjectRetention",
	"s3-object-lambda:PutObjectTagging",
	"s3-object-lambda:PutObjectVersionAcl",
	"s3-object-lambda:PutObjectVersionTagging",
	"s3-object-lambda:ReplicateObject",
	"s3-object-lambda:RestoreObject",

	# Amazon S3 on Outposts: AWS::S3Outposts::Object
	"s3-outposts:DeleteObject",
	"s3-outposts:DeleteObjectTagging",
	"s3-outposts:DeleteObjectVersion",
	"s3-outposts:DeleteObjectVersionTagging",
	"s3-outposts:GetObject",
	"s3-outposts:GetObjectAcl",
	"s3-outposts:GetObjectAttributes",
	"s3-outposts:GetObjectLegalHold",
	"s3-outposts:GetObjectRetention",
	"s3-outposts:GetObjectTagging",
	"s3-outposts:GetObjectTorrent",
	"s3-outposts:GetObjectVersion",
	"s3-outposts:GetObjectVersionAcl",
	"s3-outposts:GetObjectVersionAttributes",
	"s3-outposts:GetObjectVersionForReplication",
	"s3-outposts:GetObjectVersionTagging",
	"s3-outposts:GetObjectVersionTorrent",
	"s3-outposts:PutObject",
	"s3-outposts:PutObjectAcl",
	"s3-outposts:PutObjectLegalHold",
	"s3-outposts:PutObjectRetention",
	"s3-outposts:PutObjectTagging",
	"s3-outposts:PutObjectVersionAcl",
	"s3-outposts:PutObjectVersionTagging",
	"s3-outposts:ReplicateObject",
	"s3-outposts:RestoreObject",

	# AWS CloudTrail: AWS::CloudTrail::Channel
	"cloudtrail-data:PutAuditEvents",

	# Amazon Cognito: AWS::Cognito::IdentityPool
	"cognito-identity:GetCredentialsForIdentity",
	"cognito-identity:GetId",
	"cognito-identity:GetOpenIdToken",
	"cognito-identity:GetOpenIdTokenForDeveloperIdentity",
	"cognito-identity:UnlinkIdentity",

	# Amazon Elastic Block Store: AWS::EC2::Snapshot
	"ebs:ListSnapshotBlocks",
	"ebs:ListChangedBlocks",
	"ebs:GetSnapshotBlock",
	"ebs:PutSnapshotBlock",

	# Amazon FinSpace: AWS::FinSpace::Environment
	"finspace-api:GetObject",

	# AWS Glue: AWS::Glue::Table
	# AWS Glue API activity on tables that were created by Lake Formation.

	# Amazon GuardDuty: AWS::GuardDuty::Detector
	# This applies to the data events generated by the security agent.

	# Amazon Kendra Intelligent Ranking: AWS::KendraRanking::ExecutionPlan
	"kendra-ranking:Rescore",

	# Amazon Managed Blockchain: AWS::ManagedBlockchain::Node
	# It seems like the eventNames here are 'web3_clientVersion'
	# https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/logging-using-cloudtrail.html#ethereum-jsonrpc-logging

	# Amazon SageMaker: AWS::SageMaker::FeatureGroup
	# https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store-logging-using-cloudtrail.html
	"sagemaker:BatchGetRecord",
	"sagemaker:DeleteRecord",
	"sagemaker:GetRecord",
	"sagemaker:PutRecord",

	# Amazon SageMaker: AWS::SageMaker::ExperimentTrialComponent
	# https://docs.aws.amazon.com/sagemaker/latest/dg/experiments-monitoring.html
	"sagemaker:BatchPutMetrics",
]